# Generated by Django 6.0.2 on 2026-03-25 21:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0001_initial'),
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evaluacion', models.CharField(choices=[('PR', 'Prueba'), ('TA', 'Tarea'), ('EX', 'Examen'), ('TR', 'Trabajo'), ('PS', 'Presentación'), ('OT', 'Otro')], max_length=2, verbose_name='Tipo de Evaluación')),
                ('nota', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(7.0)], verbose_name='Nota')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='alumnos.alumno', verbose_name='Alumno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='cursos.curso', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'ordering': ['-fecha', 'alumno'],
            },
        ),
    ]
