# Generated by Django 6.0.2 on 2026-03-26 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('tipo', models.CharField(choices=[('CI', 'Circular'), ('AV', 'Aviso'), ('UR', 'Urgente')], default='AV', max_length=2, verbose_name='Tipo')),
                ('destinatarios', models.CharField(choices=[('TO', 'Todos'), ('CU', 'Por curso'), ('AP', 'Solo apoderados'), ('PR', 'Solo profesores')], default='TO', max_length=2, verbose_name='Destinatarios')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de publicación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comunicados', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('curso', models.ForeignKey(blank=True, help_text="Solo si los destinatarios son 'Por curso'", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comunicados', to='cursos.curso', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Comunicado',
                'verbose_name_plural': 'Comunicados',
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
