# Generated by Django 6.0.2 on 2026-03-26 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profesores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('SUPER', 'Superusuario'), ('DIRECTOR', 'Director'), ('SECRETARIA', 'Secretaria / Administrativo'), ('PROFESOR', 'Profesor')], max_length=20, verbose_name='Rol')),
                ('profesor', models.OneToOneField(blank=True, help_text='Solo si el rol es Profesor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_usuario', to='profesores.profesor', verbose_name='Profesor vinculado')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfiles de usuario',
            },
        ),
    ]
