# Generated by Django 6.0.2 on 2026-03-08 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='RUT')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('profesion', models.CharField(max_length=150, verbose_name='Profesión')),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
                'ordering': ['apellido', 'nombre'],
            },
        ),
    ]
